### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by zaheerk89** [r0oth3x49/cbtnuggets-dl#3]
[*] : Downloading course information webpages ..
Traceback (most recent call last):
  File "cbtnuggets-dl.py", line 319, in <module>
    main()
  File "cbtnuggets-dl.py", line 254, in main
    cbtnuggets.ExtractAndDownload()
  File "cbtnuggets-dl.py", line 122, in ExtractAndDownload
    videos  = extract_info.real_extract(self.url, course_name, course_path, access_token)
  File "/root/cbtnuggets-dl-master/cbtnuggets/_extractor.py", line 133, in real_extract
    course_id,json_string = self._get_course_id(response.text)
  File "/root/cbtnuggets-dl-master/cbtnuggets/_extractor.py", line 58, in _get_course_id
    json_string     = json.loads(webpage.split('courseInfoJSON: ')[1].split(",\r\n")[0])
  File "/opt/rh/python27/root/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/python27/root/usr/lib64/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 8822 - line 46 column 1 (char 8821 - 25075)

**Comment by r0oth3x49** [comment]
@zaheerk89 i don't have cbtnugget account to test against.
