### ISSUE TITLE
Can't download last lecture in course: AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by RecQuery** [r0oth3x49/cbtnuggets-dl#7]
Hi,

I'm trying to download a lecture in a course and repeatedly get the following error:

```
[*] : Downloading lecture : (220 of 228)
[*] : Downloading (220 Troubleshooting Wireless: The Nature of Airwaves)
Traceback (most recent call last):
  File "cbtnuggets-dl.py", line 321, in <module>
    main()
  File "cbtnuggets-dl.py", line 275, in main
    cbtnuggets.ExtractAndDownload()
  File "cbtnuggets-dl.py", line 171, in ExtractAndDownload
    _url_json   = req_res.get('10x') if req_res.get('10x') else req_res['error'].get('status')
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by RecQuery** [comment]
Looking into this further it turns out videos 220 to 224 haven't been created yet.

Is there a way to skip videos? or to have it automatically try the next one?

**Comment by r0oth3x49** [comment]
@RecQuery i might need your account to test and fix. [email me](mailto:nasir251292@gmail.com) if you don't have a problem with sharing creds
