### ISSUE TITLE
Course download doesn't start: IndexError: list index out of range

### ISSUE THREAD

**Issue by RecQuery** [r0oth3x49/cbtnuggets-dl#8]
Hi,

I'm trying to download the following course but it won't even start: https://www.cbtnuggets.com/it-training/microsoft-windows-10-70-697-configuring-windows-devices

```
[*] : Downloading 'microsoft windows 10 70 697 configuring windows devices'.
[*] : Trying to login as (name@gmail.com)...
[+] : Logged in successfully.
[*] : Downloading course information webpages ..
Traceback (most recent call last):
  File "cbtnuggets-dl.py", line 321, in <module>
    main()
  File "cbtnuggets-dl.py", line 275, in main
    cbtnuggets.ExtractAndDownload()
  File "cbtnuggets-dl.py", line 123, in ExtractAndDownload
    videos  = extract_info.real_extract(self.url, course_name, course_path, access_token)
  File "C:\Python27\cbtnuggets\_extractor.py", line 148, in real_extract
    course_id,json_string = self._get_course_info(response)
  File "C:\Python27\cbtnuggets\_extractor.py", line 72, in _get_course_info
    course_id       = webpage.split("CBTNCollectionId : '")[1].split("',")[0]
IndexError: list index out of range
```

**Comment by r0oth3x49** [comment]
@RecQuery i 'm going to close this issue as you are not active and no other user are facing the problem. will wait for others to report the same
